language: node_js

node_js:
  - "lts/erbium"
  - "node"

env:
  API_KEY=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

install:
  - yarn

os:
  - "linux"

jobs:
  include:
    - stage: "Coverage"
      name: "Code Coverage"
      script: 
        - yarn coverage
        - yarn codecov
