language: node_js

node_js:
  - "lts/erbium"
  - "node"

env:
  API_KEY=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

before_install:
  - mv .env.sample .env

install:
  - yarn

os:
  - "linux"

jobs:
  include:
    - stage: test
      script:
        - yarn test
    - stage: coverage
      script:
        - yarn coverage
        - yarn codecov
