language: node_js

node_js:
  - "lts/erbium"
  - "node"

sudo: false

install:
  - yarn

os:
  - "linux"
  - "osx"

jobs:
  include:
    - stage: test
      script:
        - yarn test
    - stage: coverage
      script:
        - yarn coverage
        - yarn codecov
