language: node_js

install:
  - yarn
  - npm install -g codecov

jobs:
  include:
    - state: test
      node_js:
        - 11
      script:
        - yarn test
    - stage: coverage
      node_js: "11"
      script:
        - yarn coverage
        - codecov
